steps:
  # Instalando dependencias
- name: node:14
  entrypoint: npm
  args: ["install"]
  # Construyendo aplicacion
- name: node:14
  entrypoint: npm
  args: ["run", "build"]
  # Deploy
- name: "gcr.io/cloud-builders/gcloud"
  env:
    - "BRANCH=master"
  args:
    - "app"
    - "deploy"
    - "--appyaml=app-${BRANCH}.yaml"
timeout: "1600s"
